import sqlite3


DATABASE_NAME = "metragaurd.db"


def get_connection():
    return sqlite3.connect(DATABASE_NAME)


def create_table():
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS inspections (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            filename TEXT,
            compliance_status TEXT,
            compliance_score INTEGER,
            extracted_text TEXT,
            violations TEXT
        )
    """)

    connection.commit()
    connection.close()


def save_inspection(
    filename,
    compliance_status,
    compliance_score,
    extracted_text,
    violations
):
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        INSERT INTO inspections (
            filename,
            compliance_status,
            compliance_score,
            extracted_text,
            violations
        )
        VALUES (?, ?, ?, ?, ?)
    """, (
        filename,
        compliance_status,
        compliance_score,
        extracted_text,
        "\n".join(violations)
    ))

    connection.commit()

    inspection_id = cursor.lastrowid

    connection.close()

    return inspection_id


def get_inspections():
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT
            id,
            filename,
            compliance_status,
            compliance_score,
            violations
        FROM inspections
        ORDER BY id DESC
    """)

    rows = cursor.fetchall()
    connection.close()

    return rows

def get_inspection_by_id(inspection_id):
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT
            id,
            filename,
            compliance_status,
            compliance_score,
            extracted_text,
            violations
        FROM inspections
        WHERE id = ?
    """, (inspection_id,))

    inspection = cursor.fetchone()

    connection.close()

    return inspection   

def generate_report(inspection_id):
    inspection = get_inspection_by_id(inspection_id)

    if inspection is None:
        return None

    report = f"""
METRAGUARD
LEGAL METROLOGY INSPECTION REPORT
=================================

Inspection ID: {inspection[0]}
Product Image: {inspection[1]}

Compliance Status: {inspection[2]}
Detection Score: {inspection[3]}%

---------------------------------
POTENTIAL ISSUES
---------------------------------

"""

    if inspection[5]:
        for violation in inspection[5].split("\n"):
            report += f"- {violation}\n"
    else:
        report += "No potential issues detected.\n"

    report += """
---------------------------------
RECOMMENDATION
---------------------------------

This automated screening result should be
manually verified by an authorized
enforcement official before taking action.

=================================
Generated by Metraguard
"""

    return report